//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoldDiff.View.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LoLStaticResourceCacheResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoLStaticResourceCacheResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GoldDiff.View.Resource.LoLStaticResourceCacheResources", typeof(LoLStaticResourceCacheResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates ....
        /// </summary>
        public static string CheckForUpdatesProgressStepDescription {
            get {
                return ResourceManager.GetString("CheckForUpdatesProgressStepDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating champion index ....
        /// </summary>
        public static string CreateChampionIndexProgressStepDescription {
            get {
                return ResourceManager.GetString("CreateChampionIndexProgressStepDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating item index ....
        /// </summary>
        public static string CreateItemIndexProgressStepDescription {
            get {
                return ResourceManager.GetString("CreateItemIndexProgressStepDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting older resources ....
        /// </summary>
        public static string DeleteOldStatisResourcesProgressStepDescription {
            get {
                return ResourceManager.GetString("DeleteOldStatisResourcesProgressStepDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting resource archive ....
        /// </summary>
        public static string DeleteResourceArchiveProgressStepDescription {
            get {
                return ResourceManager.GetString("DeleteResourceArchiveProgressStepDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading resources ....
        /// </summary>
        public static string DownloadStaticResourcesProgressStepDescription {
            get {
                return ResourceManager.GetString("DownloadStaticResourcesProgressStepDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETA.
        /// </summary>
        public static string DownloadStaticResourcesRemainingTime {
            get {
                return ResourceManager.GetString("DownloadStaticResourcesRemainingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpacking resources ....
        /// </summary>
        public static string ExtractStaticResourcesProgressStepDescription {
            get {
                return ResourceManager.GetString("ExtractStaticResourcesProgressStepDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Resources.
        /// </summary>
        public static string UpdateProgressTitle {
            get {
                return ResourceManager.GetString("UpdateProgressTitle", resourceCulture);
            }
        }
    }
}
