//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoldDiff.View.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewSettingsDialogResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewSettingsDialogResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GoldDiff.View.Resource.ViewSettingsDialogResources", typeof(ViewSettingsDialogResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes are applied after the next restart..
        /// </summary>
        public static string HintRestartIsRequired {
            get {
                return ResourceManager.GetString("HintRestartIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string LabelAppearanceSettings {
            get {
                return ResourceManager.GetString("LabelAppearanceSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Inhibitor Respawn Time.
        /// </summary>
        public static string LabelDisplayInhibitorRespawnTimers {
            get {
                return ResourceManager.GetString("LabelDisplayInhibitorRespawnTimers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show KDA.
        /// </summary>
        public static string LabelDisplayPlayerScores {
            get {
                return ResourceManager.GetString("LabelDisplayPlayerScores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Unspent KDA.
        /// </summary>
        public static string LabelDisplayPlayerScoresSinceLastItemAcquisition {
            get {
                return ResourceManager.GetString("LabelDisplayPlayerScoresSinceLastItemAcquisition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show KDA.
        /// </summary>
        public static string LabelDisplayTeamScores {
            get {
                return ResourceManager.GetString("LabelDisplayTeamScores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Unspent KDA.
        /// </summary>
        public static string LabelDisplayTeamScoresSinceLastItemAcquisition {
            get {
                return ResourceManager.GetString("LabelDisplayTeamScoresSinceLastItemAcquisition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Window Title.
        /// </summary>
        public static string LabelDisplayTitleBar {
            get {
                return ResourceManager.GetString("LabelDisplayTitleBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Display.
        /// </summary>
        public static string LabelGameDisplaySettings {
            get {
                return ResourceManager.GetString("LabelGameDisplaySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold Type.
        /// </summary>
        public static string LabelGoldType {
            get {
                return ResourceManager.GetString("LabelGoldType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Display.
        /// </summary>
        public static string LabelPlayerDisplaySettings {
            get {
                return ResourceManager.GetString("LabelPlayerDisplaySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay on Top.
        /// </summary>
        public static string LabelStayOnTop {
            get {
                return ResourceManager.GetString("LabelStayOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Display.
        /// </summary>
        public static string LabelTeamDisplaySettings {
            get {
                return ResourceManager.GetString("LabelTeamDisplaySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string LabelTheme {
            get {
                return ResourceManager.GetString("LabelTheme", resourceCulture);
            }
        }
    }
}
